language: bash
sudo: required
services:
- docker
script:
- |
  if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
    openssl aes-256-cbc -K $encrypted_6dcdd37ad8d6_key -iv $encrypted_6dcdd37ad8d6_iv -in secret-mojp-k8s-ops.json.enc -out k8s-ops-secret.json -d &&\
    git clone --depth 1 https://github.com/Beit-Hatfutsot/mojp-k8s.git &&\
    docker pull orihoch/mojp-k8s &&\
    docker run -it -v "`pwd`/k8s-ops-secret.json:/k8s-ops/secret.json" \
                   -v "`pwd`/mojp-k8s:/ops" \
                   orihoch/mojp-k8s \
                   -c "source ~/.bashrc; source switch_environment.sh production; \
                      kubectl get pods \
                      ";
  else
    true
  fi
